Completed removal of Windows Proccesses
Windows is not a likely target for use

diff --git a/.github/workflows/swift_package_test.yml b/.github/workflows/swift_package_test.yml
--- a/.github/workflows/swift_package_test.yml
+++ b/.github/workflows/swift_package_test.yml
@@ -100,90 +100,91 @@ jobs:
       - name: Build / Test
         run: ${{ inputs.linux_build_command }} ${{ (contains(matrix.swift_version, 'nightly') && inputs.swift_nightly_flags) || inputs.swift_flags }}
 
-  windows-build:
-    name: Windows (${{ matrix.swift_version }} - ${{ inputs.enable_windows_docker && contains(matrix.swift_version, 'nightly') && 'windows-2019' || 'windows-2022' }})
-    if: ${{ inputs.enable_windows_checks }}
-    runs-on: ${{ inputs.enable_windows_docker && contains(matrix.swift_version, 'nightly') && 'windows-2019' || 'windows-2022' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        swift_version: ['5.9', '6.0', 'nightly', 'nightly-6.1']
-        exclude:
-          - ${{ fromJson(inputs.windows_exclude_swift_versions) }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Provide token
-        if: ${{ inputs.needs_token }}
-        run: |
-          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
-      - name: Set environment variables
-        if: ${{ inputs.windows_env_vars }}
-        run: |
-          $lines = "${{ inputs.windows_env_vars }}" -split "`r`n"
-          foreach ($line in $lines) {
-              echo $line | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
-          }
-      - name: Pull Docker image
-        id: pull_docker_image
-        if: ${{ inputs.enable_windows_docker }}
-        run: |
-          if ("${{ matrix.swift_version }}".Contains("nightly")) {
-            $Image = "swiftlang/swift:${{ matrix.swift_version }}-windowsservercore-1809"
-          } else {
-            $Image = "swift:${{ matrix.swift_version }}-windowsservercore-ltsc2022"
-          }
-          docker pull $Image
-          echo "image=$Image" >> "$env:GITHUB_OUTPUT"
-      - name: Install Visual Studio Build Tools
-        if: ${{ !inputs.enable_windows_docker }}
-        run: |
-          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/install-vsb.ps1 -OutFile $env:TEMP\install-vsb.ps1
-          . $env:TEMP\install-vsb.ps1
-          del $env:TEMP\install-vsb.ps1
-      - name: Install Swift
-        if: ${{ !inputs.enable_windows_docker }}
-        run: |
-          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift.ps1 -OutFile $env:TEMP\install-swift.ps1
-          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift-${{ matrix.swift_version }}.ps1 -OutFile $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
-          . $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
-          del $env:TEMP\install-swift*.ps1
-      - name: Create test script
-        run: |
-          mkdir $env:TEMP\test-script
-          echo @'
-          Set-PSDebug -Trace 1
-          if ("${{ inputs.enable_windows_docker }}" -eq "true") {
-            $Source = "C:\source"
-          } else {
-            $Source = $env:GITHUB_WORKSPACE
-          }
-
-          # Run the command following `Invoke-Program`.
-          # If that command returns a non-zero exit code, return the same exit code from this script.
-          function Invoke-Program($Executable) {
-            & $Executable @args
-            if ($LastExitCode -ne 0) {
-              exit $LastExitCode
-            }
-          }
-          Invoke-Program swift --version
-          Invoke-Program swift test --version
-          Invoke-Program cd $Source
-          ${{ inputs.windows_pre_build_command }}
-          Invoke-Program ${{ inputs.windows_build_command }} ${{ (contains(matrix.swift_version, 'nightly') && inputs.swift_nightly_flags) || inputs.swift_flags }}
-          '@ >> $env:TEMP\test-script\run.ps1
-      # Docker build
-      - name: Docker Build / Test
-        timeout-minutes: 60
-        if: ${{ inputs.enable_windows_docker }}
-        run: |
-          docker run -v ${{ github.workspace }}:C:\source -v $env:TEMP\test-script:C:\test-script ${{ steps.pull_docker_image.outputs.image }} powershell.exe -NoLogo -File C:\test-script\run.ps1
+#  windows-build:
+#    name: Windows (${{ matrix.swift_version }} - ${{ inputs.enable_windows_docker && contains(matrix.swift_version, 'nightly') && 'windows-2019' || 'windows-2022' }})
+#    if: ${{ inputs.enable_windows_checks }}
+#    runs-on: ${{ inputs.enable_windows_docker && contains(matrix.swift_version, 'nightly') && 'windows-2019' || 'windows-2022' }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        swift_version: ['5.9', '6.0', 'nightly', 'nightly-6.1']
+#        exclude:
+#          - ${{ fromJson(inputs.windows_exclude_swift_versions) }}
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v4
+#      - name: Provide token
+#        if: ${{ inputs.needs_token }}
+#        run: |
+#          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+#      - name: Set environment variables
+#        if: ${{ inputs.windows_env_vars }}
+#        run: |
+#          $lines = "${{ inputs.windows_env_vars }}" -split "`r`n"
+#          foreach ($line in $lines) {
+#              echo $line | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
+#          }
+#      - name: Pull Docker image
+#        id: pull_docker_image
+#        if: ${{ inputs.enable_windows_docker }}
+#        run: |
+#          if ("${{ matrix.swift_version }}".Contains("nightly")) {
+#            $Image = "swiftlang/swift:${{ matrix.swift_version }}-windowsservercore-1809"
+#          } else {
+#            $Image = "swift:${{ matrix.swift_version }}-windowsservercore-ltsc2022"
+#          }
+#          docker pull $Image
+#          echo "image=$Image" >> "$env:GITHUB_OUTPUT"
+#      - name: Install Visual Studio Build Tools
+#        if: ${{ !inputs.enable_windows_docker }}
+#        run: |
+#          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/install-vsb.ps1 -OutFile $env:TEMP\install-vsb.ps1
+#          . $env:TEMP\install-vsb.ps1
+#          del $env:TEMP\install-vsb.ps1
+#      - name: Install Swift
+#        if: ${{ !inputs.enable_windows_docker }}
+#        run: |
+#          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift.ps1 -OutFile $env:TEMP\install-swift.ps1
+#          Invoke-WebRequest -Uri https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/windows/swift/install-swift-${{ matrix.swift_version }}.ps1 -OutFile $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
+#          . $env:TEMP\install-swift-${{ matrix.swift_version }}.ps1
+#          del $env:TEMP\install-swift*.ps1
+#      - name: Create test script
+#        run: |
+#          mkdir $env:TEMP\test-script
+#          echo @'
+#          Set-PSDebug -Trace 1
+#          if ("${{ inputs.enable_windows_docker }}" -eq "true") {
+#            $Source = "C:\source"
+#          } else {
+#            $Source = $env:GITHUB_WORKSPACE
+#          }
+#
+#          # Run the command following `Invoke-Program`.
+#          # If that command returns a non-zero exit code, return the same exit code from this script.
+#          function Invoke-Program($Executable) {
+#            & $Executable @args
+#            if ($LastExitCode -ne 0) {
+#              exit $LastExitCode
+#            }
+#          }
+#          Invoke-Program swift --version
+#          Invoke-Program swift test --version
+#          Invoke-Program cd $Source
+#          ${{ inputs.windows_pre_build_command }}
+#          Invoke-Program ${{ inputs.windows_build_command }} ${{ (contains(matrix.swift_version, 'nightly') && inputs.swift_nightly_flags) || inputs.swift_flags }}
+#          '@ >> $env:TEMP\test-script\run.ps1
+#      # Docker build
+#      - name: Docker Build / Test
+#        timeout-minutes: 60
+#        if: ${{ inputs.enable_windows_docker }}
+#        run: |
+#          docker run -v ${{ github.workspace }}:C:\source -v $env:TEMP\test-script:C:\test-script ${{ steps.pull_docker_image.outputs.image }} powershell.exe -NoLogo -File C:\test-script\run.ps1
       # Docker-less build
-      - name: Build / Test
-        timeout-minutes: 60
-        if: ${{ !inputs.enable_windows_docker }}
-        run: |
-          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
-          RefreshEnv
-          powershell.exe -NoLogo -File $env:TEMP\test-script\run.ps1; exit $LastExitCode
+#      - name: Build / Test
+#        timeout-minutes: 60
+#        if: ${{ !inputs.enable_windows_docker }}
+#        run: |
+#          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
+#          RefreshEnv
+#          powershell.exe -NoLogo -File $env:TEMP\test-script\run.ps1; exit $LastExitCode
+#
